#!/bin/bash

#Configure a proper user
#Usage:  set-user username "Full Name" e-mail
#Pre-requisites: git and docker installed 

if [ "$#" -ne 3 ]; then
    echo "Usage: set-user username \"Full Name\"" e-mail
    exit 1 
fi

sudo adduser --gecos "$2" $1
sudo sed -e "\$a$1 ALL=(ALL) ALL" -i /etc/sudoers
sudo usermod -aG docker $USER
git config --global --add user.name "$2"
git config --global --add user.email "$1@$3.com"
git config --global --list

cd
mkdir golang
mkdir golang/src
echo "export GOPATH=/home/$USER/golang" >>.bashrc



cd  
sudo sed "s/localhost/localhost `hostname`/" -i /etc/hosts 

sudo gpasswd -a $1 docker
sudo gpasswd -a $1 plugdev #is it really required?
sudo gpasswd -a $1 netdev
sudo cp -r .ssh /home/$1
sudo chown $1:$1 /home/$1/.ssh
sudo chown $1:$1 /home/$1/.ssh/authorized_keys
sudo cp ./.Xauthority /home/$1
sudo chown $1:$1 /home/$1/.Xauthority

if [[ "$3" == ?*@?* ]] ; then
 email=$3 
else if [[ "$1" == ?*.com ]] ; then
 email="$1@$3" 
else
 email="$1@$3.com" 
fi
fi

git config --global --add user.name "$2"
git config --global --add user.email "$email"

sudo cp .gitconfig /home/$1
sudo chown $1:$1 /home/$1/.gitconfig

