#!/bin/bash

SERVICE_NAME=$1
SERVICE_PATH=$2
SERVICE_PORT=$3

.docker/service/wait $SERVICE_NAME

curl "$PROXY_ENDPOINT/reconfigure?serviceName=$SERVICE_NAME&servicePath=/$SERVICE_PATH&port=$SERVICE_PORT"

