#!/bin/bash

LEADER=$1

docker network create --driver overlay proxy
docker service create --name proxy            \
	-p 80:80                              \
	-p 443:443                            \
	-p 8080:8080			      \
	--network proxy                       \
	--constraint node.hostname=="$LEADER" \
	-e MODE=swarm                         \
	vfarcic/docker-flow-proxy

