#!/bin/bash

sudo usermod -aG docker $USER
NAME=`getent passwd $USER | cut -d ':' -f 5 | cut -d ',' -f 1`
EMAIL=$USER@$1.com
sudo cat >/home/$USER/.gitconfig <<EOF
[user]
	name = $NAME
	email = $EMAIL
EOF
git config --global --list

cd
mkdir -p golang/src
echo "export GOPATH=/home/$USER/golang" >>.bashrc
echo "export GOPATH=/home/$USER/golang" >>.profile
echo "export GOROOT=/usr/lib/go" >>.bashrc
echo "export GOROOT=/usr/lib/go" >>.profile

echo 'PS1="\[\033[01;34m\]\w\[\033[00m\]\$ "' >>.bashrc
sudo reboot

