#!/bin/bash

cd /tmp
export VERSION=2016.2
export NAME=ideaIC-$VERSION
export ARCHIVE=$NAME.tar.gz
wget https://download.jetbrains.com/idea/$ARCHIVE
tar -xvf $ARCHIVE
export FOLDER=idea-IC-162.1121.32
sudo mv $FOLDER /opt
sudo ln -sf /opt/$FOLDER /opt/idea
sudo ln -s /opt/idea/bin/idea.sh /usr/local/bin/idea
idea

