#!/bin/bash

KEY_FILE=$1
BASTION=$2
SLAVE=$3

cat >>~/.ssh/config <<EOF
Host $SLAVE
	StrictHostKeyChecking no
	UserKnownHostsFile=/dev/null
	IdentityFile ~/.ssh/$KEY_FILE
	ProxyCommand ssh -q cloud-user@$BASTION -W %h:%p	
EOF

