#!/bin/bash

KEY_FILE=$1
BASTION=$2
SOCKS_PORT=$3

rm -f ~/.ssh/*
cat >~/.ssh/config <<EOF
Host $BASTION
	ForwardAgent yes
	StrictHostKeyChecking no
	UserKnownHostsFile=/dev/null
	IdentityFile ~/.ssh/$KEY_FILE
EOF
cp ~/Downloads/$KEY_FILE ~/.ssh
chmod 600 ~/.ssh/*
ssh -D $SOCKS_PORT -f -C -q -N cloud-user@$BASTION

