#!/bin/bash

KEY_FILE=$1
BASTION=$2

rm -f ~/.ssh/*
cat >~/.ssh/config <<EOF
Host $BASTION
	ForwardAgent yes
	StrictHostKeyChecking no
	UserKnownHostsFile=/dev/null
	IdentityFile ~/.ssh/$KEY_FILE
EOF
cp ~/Downloads/$KEY_FILE ~/.ssh
chmod 600 ~/.ssh/*
ssh -D 8123 -f -C -q -N cloud-user@$BASTION
export ALL_PROXY=socks5://localhost:8123
export all_proxy=socks5://localhost:8123

