#!/bin/bash

BASTION=$1
MASTER=$2
REGISTRY=$3
CERT_DIR=$4
CERT_FILE=$5

sudo sh -c "echo \"$MASTER  $REGISTRY\" >>/etc/hosts"
sudo mkdir -p $CERT_DIR
sudo mv $CERT_FILE $CERT_DIR
sudo service docker restart


