#!/bin/bash

MASTER=$1
DOCKER_PORT=$2
MASTER_HOST=$3
REGISTRY_TAG=$4
HOSTNAME=$5

sudo hostnamectl set-hostname $HOSTNAME
sudo sh -c "echo $MASTER $MASTER_HOST >>/etc/hosts"

sudo sed -e "s/ExecStart=.*/ExecStart=\/usr\/bin\/dockerd -H tcp:\/\/0.0.0.0:$DOCKER_PORT --insecure-registry=$REGISTRY_TAG/" -i /usr/lib/systemd/system/docker.service

sudo systemctl --system daemon-reload
sudo service docker restart

