#!/bin/bash

MASTER=$1
DOCKER_PORT=$2

export DOCKER_HOST="tcp://$MASTER:$DOCKER_PORT" 
docker swarm init --advertise-addr $MASTER | grep -A 4 "To add a worker" /tmp/out | tail -4 | tr -d '\\\\' | tr -s ' ' | tr -d '\r' | tr -d '\n'


