#!/bin/bash

#PROXY=$1
#MASTER_HOST=$2

docker network create --driver overlay $PROXY
docker service create --name $PROXY           \
	-p 80:80                              \
	-p 443:443                            \
	-p 8080:8080			      \
	--network $PROXY                      \
	-e MODE=swarm                         \
	vfarcic/docker-flow-proxy


