#!/bin/bash

KEY_FILE=$1.pem
export BASTION=$2
export MASTER=$3
export SLAVE1=$4
export SLAVE2=$5
export SLAVE3=$6

rm ~/.ssh/*
cp ~/Downloads/$KEY_FILE ~/.ssh
#TODO: loop over nodes
cat >~/.ssh/config <<EOF
Host $BASTION
	ForwardAgent yes
	StrictHostKeyChecking no
	UserKnownHostsFile=/dev/null
	IdentityFile ~/.ssh/$KEY_FILE
Host $MASTER
	StrictHostKeyChecking no
	UserKnownHostsFile=/dev/null
	IdentityFile ~/.ssh/$KEY_FILE
	ProxyCommand ssh -q cloud-user@$BASTION -W %h:%p
Host $SLAVE1
	StrictHostKeyChecking no
	UserKnownHostsFile=/dev/null
	IdentityFile ~/.ssh/$KEY_FILE
	ProxyCommand ssh -q cloud-user@$BASTION -W %h:%p
Host $SLAVE2
	StrictHostKeyChecking no
	UserKnownHostsFile=/dev/null
	IdentityFile ~/.ssh/$KEY_FILE
	ProxyCommand ssh -q cloud-user@$BASTION -W %h:%p
Host $SLAVE3
	StrictHostKeyChecking no
	UserKnownHostsFile=/dev/null
	IdentityFile ~/.ssh/$KEY_FILE
	ProxyCommand ssh -q cloud-user@$BASTION -W %h:%p
EOF
chmod 600 ~/.ssh/*

