#!/bin/bash

export BASTION=$1
export KEY_FILE=~/Downloads/cloud-user.pem
chmod 600 $KEY_FILE
rm ~/.ssh/*
./config-ssh

ssh-agent /bin/sh <<EOF
ssh-add $KEY_FILE
ssh cloud-user@$BASTION "bash -s" <<EOF1
echo "Host *" >~/.ssh/config
echo "	ForwardAgent yes" >>~/.ssh/config 
echo "	StrictHostKeyChecking no" >>~/.ssh/config 
echo "	UserKnownHostsFile=/dev/null" >>~/.ssh/config 
chmod 600 ~/.ssh/config
EOF1
EOF





