#!/bin/bash

sudo sh -c "curl -L https://github.com/docker/machine/releases/download/0.8.0/docker-machine-`uname -s`-`uname -m` >/usr/local/bin/docker-machine"
sudo chmod +x /usr/local/bin/docker-machine
