#!/bin/bash

export BASTION=$1
export MASTER=$2
export KEY_FILE=~/Downloads/cloud-user.pem

ssh-agent /bin/sh <<EOF
ssh-add $KEY_FILE
ssh -A -t cloud-user@$BASTION ssh -t cloud-user@$MASTER docker node ls 
EOF

