#!/bin/bash

export CLUSTER=$1
KEY_FILE=$CLUSTER.pem
export BASTION=$2
export MASTER=$3
export MASTER_HOST=$CLUSTER-master

shift 3
rm -f ~/.ssh/*
cat >~/.ssh/config <<EOF
Host $BASTION
	ForwardAgent yes
	StrictHostKeyChecking no
	UserKnownHostsFile=/dev/null
	IdentityFile ~/.ssh/$KEY_FILE
EOF
for SLAVE in "$@";
do
  echo "Host $SLAVE" >> ~/.ssh/config
  cat >>~/.ssh/config <<EOF
	StrictHostKeyChecking no
	UserKnownHostsFile=/dev/null
	IdentityFile ~/.ssh/$KEY_FILE
	ProxyCommand ssh -q cloud-user@$BASTION -W %h:%p	
EOF
done

cp ~/Downloads/$KEY_FILE ~/.ssh
chmod 600 ~/.ssh/*

ssh -q cloud-user@$BASTION "sudo hostnamectl set-hostname $MASTER_HOST && sudo service docker restart"
ssh -q cloud-user@$BASTION docker swarm init --advertise-addr $MASTER > /tmp/out
JOIN=`grep -A 4 "To add a worker" /tmp/out | tail -4 | tr -d '\\\\' | tr -s ' ' | tr -d '\r' | tr -d '\n'`

i=1
for SLAVE in "$@";
do
  HOSTNAME=$(printf "%s-slave%d" $CLUSTER $i)
  ssh -q cloud-user@$SLAVE "sudo hostnamectl set-hostname $HOSTNAME && sudo service docker restart"
  ssh -q cloud-user@$SLAVE $JOIN
  let i=$i+1	
done

ssh -q cloud-user@$BASTION docker node ls



