#!/bin/bash

ssh -q -t cloud-user@$MASTER docker swarm init --advertise-addr $MASTER > /tmp/out
JOIN=`grep -A 4 "To add a worker" /tmp/out | tail -4 | tr -d '\\\\' | tr -s ' ' | tr -d '\r' | tr -d '\n'`
ssh -q -t cloud-user@$SLAVE1 $JOIN 
ssh -q -t cloud-user@$SLAVE2 $JOIN 
ssh -q -t cloud-user@$SLAVE3 $JOIN 
ssh -q -t cloud-user@$MASTER docker node ls


