#!/bin/bash

export MASTER=$1
export SLAVE1=$2
export SLAVE2=$3
export SLAVE3=$4

ssh -t cloud-user@$MASTER docker swarm init --advertise-addr $MASTER > /tmp/out
cat /tmp/out
JOIN=`grep -A 4 "To add a worker" /tmp/out | tail -4 | tr -d '\\' | tr -s ' ' | tr -d '\r' | tr -d '\n'`
echo $JOIN
ssh -t cloud-user@$SLAVE1 $JOIN 
ssh -t cloud-user@$SLAVE2 $JOIN 
ssh -t cloud-user@$SLAVE3 $JOIN 
ssh -t cloud-user@$MASTER docker node ls


