#!/bin/bash

LEADER=`docker node ls | grep Leader | cut -d ' ' -f1`
docker network create --driver overlay proxy
docker service create --name proxy       \
	-p 80:80                         \
	-p 443:443                       \
	--network proxy                  \
	--constraint node.id=="$LEADER"  \
	-e MODE=swarm                    \
	vfarcic/docker-flow-proxy
docker service ls

